# Generated by Django 3.2.16 on 2023-06-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230602_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
