# Generated by Django 3.2.16 on 2023-06-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230610_2321'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='unique_subscription',
        ),
    ]
